#!/bin/bash
#SBATCH --job-name=mpi1
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH -t 00:30:00
#SBATCH --output=mpi1.%j.out
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=mus3@gatech.edu

#run the application:
srun -N 1 --ntasks-per-node=1 ./mpi
